name             'docker'
maintainer       'Hisashi KOMINE'
maintainer_email 'hssh@hssh.jp'
license          'mit'
description      'Installs/Configures docker'
long_description 'Installs/Configures docker'
version          '0.1.0'
supports         'centos', '7.0'

depends 'selinux'
